number = int(input('Digite um número inteiro: '))
n1 = number * 1
n2 = number * 2
n3 = number * 3
n4 = number * 4
n5 = number * 5
n6 = number * 6
n7 = number * 7
n8 = number * 8
n9 = number * 9
n10 = number * 10
print('{} x 1 = {}'.format(number, n1))
print('{} x 2 = {}'.format(number, n2))
print('{} x 3 = {}'.format(number, n3))
print('{} x 4 = {}'.format(number, n4))
print('{} x 5 = {}'.format(number, n5))
print('{} x 6 = {}'.format(number, n6))
print('{} x 7 = {}'.format(number, n7))
print('{} x 8 = {}'.format(number, n8))
print('{} x 9 = {}'.format(number, n9))
print('{} x 10 = {}'.format(number, n10))
