nome = input('Qual o seu nome: ')
dia = input('Qual o dia do seu nascimento: ')
mes = input('Qual o mês do seu nascimento: ')
ano = input('Qual o ano do seu nascimento: ')
print('Bom dia {}, a data do seu nascimento é {}/{}/{}.'.format(nome, dia, mes, ano))